name: dev
type:
  - ruby

up:
  - ruby: 2.6.5
  - bundler

test:
  desc: 'Run tests.'
  run: |
    if [ "$#" -eq 1 ] && [[ -f $1 ]];
    then
      rake test TEST=$1
    else
      rake test $@
    fi

commands:
  style:
    run: bundle exec rubocop
    desc: 'Runs Rubocop'
